[2024-05-22 02:20:24,887] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 02:20:24,909] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 02:20:24,910] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:24,910] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 02:20:24,910] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:24,934] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 10:00:00+00:00
[2024-05-22 02:20:24,948] {standard_task_runner.py:52} INFO - Started process 2364 to run task
[2024-05-22 02:20:24,993] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T10:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp5vtc_wqh', '--error-file', '/tmp/tmppw3o8bmi']
[2024-05-22 02:20:25,026] {standard_task_runner.py:77} INFO - Job 12: Subtask fetch_data
[2024-05-22 02:20:25,284] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [running]> on host 8fe6997c1526
[2024-05-22 02:20:25,458] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T10:00:00+00:00
[2024-05-22 02:20:25,674] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 02:20:25,690] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 02:20:25,756] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T100000, start_date=20240522T022024, end_date=20240522T022025
[2024-05-22 02:20:25,828] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 02:20:25,931] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:14:13,396] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 04:14:13,505] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 04:14:13,508] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:13,510] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:14:13,511] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:13,636] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 10:00:00+00:00
[2024-05-22 04:14:13,737] {standard_task_runner.py:52} INFO - Started process 155 to run task
[2024-05-22 04:14:13,758] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T10:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmph43_noij', '--error-file', '/tmp/tmp377x3q7l']
[2024-05-22 04:14:13,800] {standard_task_runner.py:77} INFO - Job 13: Subtask fetch_data
[2024-05-22 04:14:14,108] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:14:14,372] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T10:00:00+00:00
[2024-05-22 04:14:14,382] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:14,423] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T100000, start_date=20240522T041413, end_date=20240522T041414
[2024-05-22 04:14:14,481] {standard_task_runner.py:92} ERROR - Failed to execute job 13 for task fetch_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:14,551] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-22 04:14:15,260] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:17:39,028] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 04:17:39,143] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 04:17:39,152] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:39,153] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:17:39,153] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:39,205] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 10:00:00+00:00
[2024-05-22 04:17:39,239] {standard_task_runner.py:52} INFO - Started process 339 to run task
[2024-05-22 04:17:39,260] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T10:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpkb2n1i7v', '--error-file', '/tmp/tmpopqv2yrr']
[2024-05-22 04:17:39,334] {standard_task_runner.py:77} INFO - Job 30: Subtask fetch_data
[2024-05-22 04:17:39,780] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:17:40,053] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T10:00:00+00:00
[2024-05-22 04:17:40,059] {logging_mixin.py:109} INFO -  api is None
[2024-05-22 04:17:40,080] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Clast_seen&location_type=0&max_age=300
[2024-05-22 04:17:40,084] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': 'None'}
[2024-05-22 04:17:40,193] {logging_mixin.py:109} INFO - Status Code: 403
[2024-05-22 04:17:40,194] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716351460,
  "error" : "ApiKeyInvalidError",
  "description" : "The provided api_key was not valid."
}
[2024-05-22 04:17:40,275] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 04:17:40,285] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 04:17:40,336] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T100000, start_date=20240522T041739, end_date=20240522T041740
[2024-05-22 04:17:40,508] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 04:17:40,662] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 06:50:11,548] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 06:50:11,629] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 06:50:11,629] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:50:11,630] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 06:50:11,630] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:50:11,726] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 10:00:00+00:00
[2024-05-22 06:50:11,855] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T10:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpmjqrq261', '--error-file', '/tmp/tmp_mg14gff']
[2024-05-22 06:50:11,794] {standard_task_runner.py:52} INFO - Started process 192 to run task
[2024-05-22 06:50:11,890] {standard_task_runner.py:77} INFO - Job 13: Subtask fetch_data
[2024-05-22 06:50:12,312] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 06:50:12,737] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T10:00:00+00:00
[2024-05-22 06:50:12,811] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 06:50:12,811] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 06:50:13,022] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 06:50:13,023] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716360613,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 06:50:13,201] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 06:50:13,202] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 06:50:13,558] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T100000, start_date=20240522T065011, end_date=20240522T065013
[2024-05-22 06:50:13,660] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 06:50:14,444] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 06:59:06,375] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 06:59:06,513] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 06:59:06,513] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:59:06,514] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 06:59:06,514] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:59:06,606] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 10:00:00+00:00
[2024-05-22 06:59:06,651] {standard_task_runner.py:52} INFO - Started process 765 to run task
[2024-05-22 06:59:06,735] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T10:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpyrmxefrz', '--error-file', '/tmp/tmpocgwnn_0']
[2024-05-22 06:59:06,747] {standard_task_runner.py:77} INFO - Job 93: Subtask fetch_data
[2024-05-22 06:59:07,008] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 06:59:07,360] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T10:00:00+00:00
[2024-05-22 06:59:07,469] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 06:59:07,484] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 06:59:07,783] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 06:59:07,783] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361147,
  "error" : "RateLimitExceededError",
  "description" : "Available API call limit exceeded, please try later."
}{
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361147,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 06:59:08,167] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 06:59:08,186] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 06:59:08,578] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T100000, start_date=20240522T065906, end_date=20240522T065908
[2024-05-22 06:59:08,861] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 06:59:09,916] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:06:55,349] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 07:06:55,459] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 07:06:55,459] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:06:55,459] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:06:55,459] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:06:55,515] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 10:00:00+00:00
[2024-05-22 07:06:55,545] {standard_task_runner.py:52} INFO - Started process 1304 to run task
[2024-05-22 07:06:55,583] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T10:00:00+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpcgjy4212', '--error-file', '/tmp/tmpklfv7pyj']
[2024-05-22 07:06:55,716] {standard_task_runner.py:77} INFO - Job 174: Subtask fetch_data
[2024-05-22 07:06:56,226] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:06:56,692] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T10:00:00+00:00
[2024-05-22 07:06:56,886] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:06:56,895] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:06:57,308] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:06:57,309] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361617,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:06:57,660] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:06:57,664] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:06:57,800] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T100000, start_date=20240522T070655, end_date=20240522T070657
[2024-05-22 07:06:58,162] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:06:58,739] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:14:10,049] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 07:14:10,186] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 07:14:10,202] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:14:10,216] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:14:10,220] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:14:10,433] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 10:00:00+00:00
[2024-05-22 07:14:10,529] {standard_task_runner.py:52} INFO - Started process 1808 to run task
[2024-05-22 07:14:10,630] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T10:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpz_0ax3u5', '--error-file', '/tmp/tmp0lsonaz5']
[2024-05-22 07:14:10,740] {standard_task_runner.py:77} INFO - Job 252: Subtask fetch_data
[2024-05-22 07:14:11,618] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:14:12,183] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T10:00:00+00:00
[2024-05-22 07:14:12,255] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:14:12,273] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:14:12,693] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:14:12,693] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362052,
  "error" : "RateLimitExceededError",
  "description" : "Available API call limit exceeded, please try later."
}{
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362052,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:14:13,192] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:14:13,199] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:14:13,347] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T100000, start_date=20240522T071410, end_date=20240522T071413
[2024-05-22 07:14:13,691] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:14:14,984] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:16:35,559] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 07:16:35,609] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 07:16:35,615] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:16:35,615] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:16:35,615] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:16:35,679] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 10:00:00+00:00
[2024-05-22 07:16:35,693] {standard_task_runner.py:52} INFO - Started process 1994 to run task
[2024-05-22 07:16:35,733] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T10:00:00+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpgnj8zphu', '--error-file', '/tmp/tmp105kmky2']
[2024-05-22 07:16:35,766] {standard_task_runner.py:77} INFO - Job 283: Subtask fetch_data
[2024-05-22 07:16:36,221] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:16:36,705] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T10:00:00+00:00
[2024-05-22 07:16:36,774] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:16:36,774] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:16:37,102] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:16:37,103] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362197,
  "error" : "RateLimitExceededError",
  "description" : "Available API call limit exceeded, please try later."
}{
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362197,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:16:37,591] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:16:37,592] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:16:37,895] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T100000, start_date=20240522T071635, end_date=20240522T071637
[2024-05-22 07:16:38,536] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:16:39,187] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:29:08,588] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 07:29:08,637] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 07:29:08,638] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:29:08,638] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:29:08,638] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:29:08,744] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 10:00:00+00:00
[2024-05-22 07:29:08,880] {standard_task_runner.py:52} INFO - Started process 2757 to run task
[2024-05-22 07:29:08,963] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T10:00:00+00:00', '--job-id', '380', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp2s4t6m_b', '--error-file', '/tmp/tmpnhl7lzwa']
[2024-05-22 07:29:09,056] {standard_task_runner.py:77} INFO - Job 380: Subtask fetch_data
[2024-05-22 07:29:09,555] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:29:10,050] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T10:00:00+00:00
[2024-05-22 07:29:10,108] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:29:10,109] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:29:10,577] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:29:10,578] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362950,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:29:10,905] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:29:10,910] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:29:11,012] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T100000, start_date=20240522T072908, end_date=20240522T072911
[2024-05-22 07:29:11,159] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:29:11,576] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:33:17,333] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 07:33:17,624] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [queued]>
[2024-05-22 07:33:17,693] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:33:17,708] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:33:17,732] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:33:17,938] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 10:00:00+00:00
[2024-05-22 07:33:18,030] {standard_task_runner.py:52} INFO - Started process 3009 to run task
[2024-05-22 07:33:18,107] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T10:00:00+00:00', '--job-id', '411', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpf3p4d3d0', '--error-file', '/tmp/tmpe1u5keys']
[2024-05-22 07:33:18,235] {standard_task_runner.py:77} INFO - Job 411: Subtask fetch_data
[2024-05-22 07:33:18,879] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T10:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:33:19,605] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T10:00:00+00:00
[2024-05-22 07:33:19,711] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:33:19,711] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:33:20,192] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:33:20,193] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716363200,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:33:20,394] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:33:20,396] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:33:20,446] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T100000, start_date=20240522T073317, end_date=20240522T073320
[2024-05-22 07:33:20,570] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:33:20,881] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
