[2024-05-22 02:20:23,972] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 02:20:24,164] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 02:20:24,164] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:24,165] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 02:20:24,165] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:24,233] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 09:00:00+00:00
[2024-05-22 02:20:24,297] {standard_task_runner.py:52} INFO - Started process 2363 to run task
[2024-05-22 02:20:24,319] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T09:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpnlk0f6m2', '--error-file', '/tmp/tmpvwphuz25']
[2024-05-22 02:20:24,363] {standard_task_runner.py:77} INFO - Job 11: Subtask fetch_data
[2024-05-22 02:20:24,886] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [running]> on host 8fe6997c1526
[2024-05-22 02:20:25,248] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T09:00:00+00:00
[2024-05-22 02:20:25,463] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 02:20:25,464] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 02:20:25,498] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T090000, start_date=20240522T022023, end_date=20240522T022025
[2024-05-22 02:20:25,603] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 02:20:25,692] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:14:11,940] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 04:14:12,114] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 04:14:12,114] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:12,114] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:14:12,115] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:12,238] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 09:00:00+00:00
[2024-05-22 04:14:12,255] {standard_task_runner.py:52} INFO - Started process 152 to run task
[2024-05-22 04:14:12,303] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T09:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpbysrn_xd', '--error-file', '/tmp/tmpp3gv07h3']
[2024-05-22 04:14:12,396] {standard_task_runner.py:77} INFO - Job 12: Subtask fetch_data
[2024-05-22 04:14:12,898] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:14:13,213] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T09:00:00+00:00
[2024-05-22 04:14:13,217] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:13,255] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T090000, start_date=20240522T041411, end_date=20240522T041413
[2024-05-22 04:14:13,305] {standard_task_runner.py:92} ERROR - Failed to execute job 12 for task fetch_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:13,352] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-22 04:14:13,532] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:17:38,947] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 04:17:39,008] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 04:17:39,008] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:39,008] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:17:39,008] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:39,093] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 09:00:00+00:00
[2024-05-22 04:17:39,133] {standard_task_runner.py:52} INFO - Started process 338 to run task
[2024-05-22 04:17:39,171] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T09:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpq_rt2fp7', '--error-file', '/tmp/tmph6o9ank4']
[2024-05-22 04:17:39,241] {standard_task_runner.py:77} INFO - Job 29: Subtask fetch_data
[2024-05-22 04:17:39,676] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:17:40,029] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T09:00:00+00:00
[2024-05-22 04:17:40,043] {logging_mixin.py:109} INFO -  api is None
[2024-05-22 04:17:40,063] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Clast_seen&location_type=0&max_age=300
[2024-05-22 04:17:40,063] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': 'None'}
[2024-05-22 04:17:40,214] {logging_mixin.py:109} INFO - Status Code: 403
[2024-05-22 04:17:40,215] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716351460,
  "error" : "ApiKeyInvalidError",
  "description" : "The provided api_key was not valid."
}
[2024-05-22 04:17:40,306] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 04:17:40,307] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 04:17:40,348] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T090000, start_date=20240522T041738, end_date=20240522T041740
[2024-05-22 04:17:40,452] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 04:17:40,558] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 06:50:11,562] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 06:50:11,641] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 06:50:11,642] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:50:11,642] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 06:50:11,642] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:50:11,757] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 09:00:00+00:00
[2024-05-22 06:50:11,766] {standard_task_runner.py:52} INFO - Started process 191 to run task
[2024-05-22 06:50:11,783] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T09:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmprtw219ip', '--error-file', '/tmp/tmpjxwu54md']
[2024-05-22 06:50:11,834] {standard_task_runner.py:77} INFO - Job 12: Subtask fetch_data
[2024-05-22 06:50:12,254] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 06:50:12,559] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T09:00:00+00:00
[2024-05-22 06:50:12,577] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 06:50:12,577] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 06:50:12,908] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 06:50:12,918] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716360612,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 06:50:17,183] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 06:50:17,184] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 06:50:17,738] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T090000, start_date=20240522T065011, end_date=20240522T065017
[2024-05-22 06:50:18,008] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 06:50:18,319] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 06:59:04,264] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 06:59:04,413] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 06:59:04,421] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:59:04,421] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 06:59:04,421] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:59:04,624] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 09:00:00+00:00
[2024-05-22 06:59:04,697] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T09:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpq6wxuekk', '--error-file', '/tmp/tmpe8ptwaqu']
[2024-05-22 06:59:04,656] {standard_task_runner.py:52} INFO - Started process 763 to run task
[2024-05-22 06:59:04,774] {standard_task_runner.py:77} INFO - Job 90: Subtask fetch_data
[2024-05-22 06:59:05,363] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 06:59:05,756] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T09:00:00+00:00
[2024-05-22 06:59:05,789] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 06:59:05,789] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 06:59:05,914] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 06:59:05,915] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361145,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 06:59:06,061] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 06:59:06,062] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 06:59:06,150] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T090000, start_date=20240522T065904, end_date=20240522T065906
[2024-05-22 06:59:06,290] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 06:59:06,513] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:06:53,276] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 07:06:53,416] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 07:06:53,421] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:06:53,424] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:06:53,425] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:06:53,544] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 09:00:00+00:00
[2024-05-22 07:06:53,578] {standard_task_runner.py:52} INFO - Started process 1296 to run task
[2024-05-22 07:06:53,658] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T09:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmphzbswv86', '--error-file', '/tmp/tmpaf6ow8dp']
[2024-05-22 07:06:53,752] {standard_task_runner.py:77} INFO - Job 171: Subtask fetch_data
[2024-05-22 07:06:54,293] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:06:54,760] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T09:00:00+00:00
[2024-05-22 07:06:54,818] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:06:54,818] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:06:55,140] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:06:55,141] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361615,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:06:55,408] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:06:55,409] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:06:55,446] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T090000, start_date=20240522T070653, end_date=20240522T070655
[2024-05-22 07:06:55,593] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:06:55,805] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:14:10,201] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 07:14:10,435] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 07:14:10,451] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:14:10,452] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:14:10,459] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:14:10,696] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 09:00:00+00:00
[2024-05-22 07:14:10,771] {standard_task_runner.py:52} INFO - Started process 1809 to run task
[2024-05-22 07:14:10,891] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T09:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp54927y2g', '--error-file', '/tmp/tmpu_f3ghew']
[2024-05-22 07:14:10,996] {standard_task_runner.py:77} INFO - Job 251: Subtask fetch_data
[2024-05-22 07:14:11,580] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:14:12,096] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T09:00:00+00:00
[2024-05-22 07:14:12,148] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:14:12,164] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:14:12,490] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:14:12,490] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362052,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:14:12,914] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:14:12,920] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:14:13,086] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T090000, start_date=20240522T071410, end_date=20240522T071413
[2024-05-22 07:14:13,488] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:14:14,984] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:16:33,709] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 07:16:33,837] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 07:16:33,838] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:16:33,838] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:16:33,838] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:16:33,996] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 09:00:00+00:00
[2024-05-22 07:16:34,024] {standard_task_runner.py:52} INFO - Started process 1991 to run task
[2024-05-22 07:16:34,075] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T09:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp8mglbl2n', '--error-file', '/tmp/tmpf56owyh_']
[2024-05-22 07:16:34,185] {standard_task_runner.py:77} INFO - Job 282: Subtask fetch_data
[2024-05-22 07:16:34,788] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:16:35,292] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T09:00:00+00:00
[2024-05-22 07:16:35,370] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:16:35,400] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:16:35,666] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:16:35,668] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362195,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:16:35,851] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:16:35,860] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:16:35,927] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T090000, start_date=20240522T071633, end_date=20240522T071635
[2024-05-22 07:16:36,109] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:16:36,385] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:29:05,145] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 07:29:05,297] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 07:29:05,304] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:29:05,312] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:29:05,313] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:29:05,557] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 09:00:00+00:00
[2024-05-22 07:29:05,606] {standard_task_runner.py:52} INFO - Started process 2750 to run task
[2024-05-22 07:29:05,721] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T09:00:00+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpn3q2rfv5', '--error-file', '/tmp/tmp0zaldovn']
[2024-05-22 07:29:05,828] {standard_task_runner.py:77} INFO - Job 376: Subtask fetch_data
[2024-05-22 07:29:06,663] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:29:07,495] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T09:00:00+00:00
[2024-05-22 07:29:07,613] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:29:07,613] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:29:08,166] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:29:08,180] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362948,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:29:08,411] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:29:08,412] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:29:08,490] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T090000, start_date=20240522T072905, end_date=20240522T072908
[2024-05-22 07:29:08,818] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:29:09,360] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:33:12,669] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 07:33:12,877] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [queued]>
[2024-05-22 07:33:12,877] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:33:12,877] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:33:12,877] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:33:13,089] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 09:00:00+00:00
[2024-05-22 07:33:13,147] {standard_task_runner.py:52} INFO - Started process 3003 to run task
[2024-05-22 07:33:13,297] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T09:00:00+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpzy286us3', '--error-file', '/tmp/tmpjni7svx0']
[2024-05-22 07:33:13,408] {standard_task_runner.py:77} INFO - Job 409: Subtask fetch_data
[2024-05-22 07:33:14,427] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T09:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:33:16,126] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T09:00:00+00:00
[2024-05-22 07:33:16,297] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:33:16,298] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:33:16,735] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:33:16,744] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716363196,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:33:17,140] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:33:17,141] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:33:17,315] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T090000, start_date=20240522T073312, end_date=20240522T073317
[2024-05-22 07:33:17,602] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:33:18,907] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
