[2024-05-22 02:20:26,062] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 02:20:26,085] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 02:20:26,086] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:26,087] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 02:20:26,087] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:26,112] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 14:00:00+00:00
[2024-05-22 02:20:26,121] {standard_task_runner.py:52} INFO - Started process 2368 to run task
[2024-05-22 02:20:26,138] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T14:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpxuk_48cn', '--error-file', '/tmp/tmp9rfivnk9']
[2024-05-22 02:20:26,154] {standard_task_runner.py:77} INFO - Job 15: Subtask fetch_data
[2024-05-22 02:20:26,269] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [running]> on host 8fe6997c1526
[2024-05-22 02:20:26,386] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T14:00:00+00:00
[2024-05-22 02:20:26,456] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 02:20:26,457] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 02:20:26,476] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T140000, start_date=20240522T022026, end_date=20240522T022026
[2024-05-22 02:20:26,547] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 02:20:26,732] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:14:14,009] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 04:14:14,081] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 04:14:14,081] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:14,081] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:14:14,081] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:14,136] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 14:00:00+00:00
[2024-05-22 04:14:14,156] {standard_task_runner.py:52} INFO - Started process 157 to run task
[2024-05-22 04:14:14,182] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T14:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp7ud129ti', '--error-file', '/tmp/tmpeun7pc_v']
[2024-05-22 04:14:14,232] {standard_task_runner.py:77} INFO - Job 16: Subtask fetch_data
[2024-05-22 04:14:14,753] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:14:14,978] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T14:00:00+00:00
[2024-05-22 04:14:14,981] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:15,027] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T140000, start_date=20240522T041414, end_date=20240522T041415
[2024-05-22 04:14:15,071] {standard_task_runner.py:92} ERROR - Failed to execute job 16 for task fetch_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:15,113] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-22 04:14:15,259] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:17:39,959] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 04:17:40,018] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 04:17:40,032] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:40,032] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:17:40,033] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:40,118] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 14:00:00+00:00
[2024-05-22 04:17:40,127] {standard_task_runner.py:52} INFO - Started process 341 to run task
[2024-05-22 04:17:40,174] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T14:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpu_hc_5ma', '--error-file', '/tmp/tmpshc4a6p6']
[2024-05-22 04:17:40,235] {standard_task_runner.py:77} INFO - Job 32: Subtask fetch_data
[2024-05-22 04:17:40,653] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:17:40,965] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T14:00:00+00:00
[2024-05-22 04:17:40,973] {logging_mixin.py:109} INFO -  api is None
[2024-05-22 04:17:40,992] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Clast_seen&location_type=0&max_age=300
[2024-05-22 04:17:40,993] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': 'None'}
[2024-05-22 04:17:41,091] {logging_mixin.py:109} INFO - Status Code: 403
[2024-05-22 04:17:41,092] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716351461,
  "error" : "ApiKeyInvalidError",
  "description" : "The provided api_key was not valid."
}
[2024-05-22 04:17:41,166] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 04:17:41,167] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 04:17:41,198] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T140000, start_date=20240522T041739, end_date=20240522T041741
[2024-05-22 04:17:41,273] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 04:17:41,349] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 06:50:12,681] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 06:50:12,763] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 06:50:12,780] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:50:12,787] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 06:50:12,787] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:50:12,847] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 14:00:00+00:00
[2024-05-22 06:50:12,908] {standard_task_runner.py:52} INFO - Started process 201 to run task
[2024-05-22 06:50:12,955] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T14:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpa65psxhw', '--error-file', '/tmp/tmpcmpld_96']
[2024-05-22 06:50:12,994] {standard_task_runner.py:77} INFO - Job 15: Subtask fetch_data
[2024-05-22 06:50:13,309] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 06:50:13,629] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T14:00:00+00:00
[2024-05-22 06:50:13,654] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 06:50:13,672] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 06:50:14,060] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 06:50:14,061] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716360614,
  "error" : "RateLimitExceededError",
  "description" : "Available API call limit exceeded, please try later."
}{
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716360614,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 06:50:14,255] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 06:50:14,272] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 06:50:14,357] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T140000, start_date=20240522T065012, end_date=20240522T065014
[2024-05-22 06:50:14,506] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 06:50:14,731] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 06:59:07,897] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 06:59:08,219] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 06:59:08,219] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:59:08,220] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 06:59:08,220] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:59:08,458] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 14:00:00+00:00
[2024-05-22 06:59:08,601] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T14:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpdezhhafi', '--error-file', '/tmp/tmpnbxn_1vj']
[2024-05-22 06:59:08,674] {standard_task_runner.py:77} INFO - Job 96: Subtask fetch_data
[2024-05-22 06:59:08,536] {standard_task_runner.py:52} INFO - Started process 781 to run task
[2024-05-22 06:59:09,459] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 06:59:09,822] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T14:00:00+00:00
[2024-05-22 06:59:09,902] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 06:59:09,902] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 06:59:10,405] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 06:59:10,406] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361150,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 06:59:10,779] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 06:59:10,857] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 06:59:11,138] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T140000, start_date=20240522T065907, end_date=20240522T065911
[2024-05-22 06:59:11,555] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 06:59:12,428] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:06:58,614] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 07:06:58,760] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 07:06:58,764] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:06:58,765] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:06:58,768] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:06:58,971] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 14:00:00+00:00
[2024-05-22 07:06:59,119] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T14:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpoboajgeb', '--error-file', '/tmp/tmp72b61cwi']
[2024-05-22 07:06:59,082] {standard_task_runner.py:52} INFO - Started process 1318 to run task
[2024-05-22 07:06:59,205] {standard_task_runner.py:77} INFO - Job 177: Subtask fetch_data
[2024-05-22 07:06:59,684] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:06:59,853] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T14:00:00+00:00
[2024-05-22 07:06:59,895] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:06:59,896] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:07:00,113] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:07:00,120] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361620,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:07:00,308] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:07:00,309] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:07:00,364] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T140000, start_date=20240522T070658, end_date=20240522T070700
[2024-05-22 07:07:00,588] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:07:00,931] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:14:16,253] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 07:14:16,532] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 07:14:16,542] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:14:16,543] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:14:16,543] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:14:16,837] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 14:00:00+00:00
[2024-05-22 07:14:16,890] {standard_task_runner.py:52} INFO - Started process 1833 to run task
[2024-05-22 07:14:16,950] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T14:00:00+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpz8uzhpv8', '--error-file', '/tmp/tmpfrxhu1fe']
[2024-05-22 07:14:17,068] {standard_task_runner.py:77} INFO - Job 257: Subtask fetch_data
[2024-05-22 07:14:17,607] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:14:18,038] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T14:00:00+00:00
[2024-05-22 07:14:18,084] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:14:18,108] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:14:18,461] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:14:18,463] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362058,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:14:18,762] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:14:18,763] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:14:18,931] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T140000, start_date=20240522T071416, end_date=20240522T071418
[2024-05-22 07:14:19,226] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:14:19,396] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:16:39,157] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 07:16:39,513] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 07:16:39,517] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:16:39,532] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:16:39,541] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:16:39,889] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 14:00:00+00:00
[2024-05-22 07:16:39,999] {standard_task_runner.py:52} INFO - Started process 2012 to run task
[2024-05-22 07:16:40,161] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T14:00:00+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpa54dof8m', '--error-file', '/tmp/tmpix62j5lo']
[2024-05-22 07:16:40,272] {standard_task_runner.py:77} INFO - Job 287: Subtask fetch_data
[2024-05-22 07:16:41,264] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:16:41,961] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T14:00:00+00:00
[2024-05-22 07:16:42,018] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:16:42,040] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:16:42,355] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:16:42,356] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362202,
  "error" : "RateLimitExceededError",
  "description" : "Available API call limit exceeded, please try later."
}{
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362202,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:16:42,659] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:16:42,711] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:16:43,462] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T140000, start_date=20240522T071639, end_date=20240522T071643
[2024-05-22 07:16:43,967] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:16:44,881] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:29:11,815] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 07:29:11,885] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 07:29:11,888] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:29:11,889] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:29:11,890] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:29:12,133] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 14:00:00+00:00
[2024-05-22 07:29:12,234] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T14:00:00+00:00', '--job-id', '383', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpxm_pzpey', '--error-file', '/tmp/tmprczu297l']
[2024-05-22 07:29:12,268] {standard_task_runner.py:77} INFO - Job 383: Subtask fetch_data
[2024-05-22 07:29:12,186] {standard_task_runner.py:52} INFO - Started process 2764 to run task
[2024-05-22 07:29:12,858] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:29:13,452] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T14:00:00+00:00
[2024-05-22 07:29:13,511] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:29:13,512] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:29:13,844] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:29:13,845] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362953,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:29:14,075] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:29:14,076] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:29:14,162] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T140000, start_date=20240522T072911, end_date=20240522T072914
[2024-05-22 07:29:14,471] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:29:14,733] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:33:20,518] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 07:33:20,627] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [queued]>
[2024-05-22 07:33:20,649] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:33:20,650] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:33:20,651] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:33:20,777] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 14:00:00+00:00
[2024-05-22 07:33:20,827] {standard_task_runner.py:52} INFO - Started process 3018 to run task
[2024-05-22 07:33:21,049] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T14:00:00+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpkh6zr4hf', '--error-file', '/tmp/tmpk5o2ssza']
[2024-05-22 07:33:21,185] {standard_task_runner.py:77} INFO - Job 415: Subtask fetch_data
[2024-05-22 07:33:21,801] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T14:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:33:22,485] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T14:00:00+00:00
[2024-05-22 07:33:22,531] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:33:22,531] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:33:22,783] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:33:22,792] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716363202,
  "error" : "RateLimitExceededError",
  "description" : "Available API call limit exceeded, please try later."
}{
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716363202,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:33:23,033] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:33:23,034] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:33:23,268] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T140000, start_date=20240522T073320, end_date=20240522T073323
[2024-05-22 07:33:23,578] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:33:24,254] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
