[2024-05-22 02:20:22,697] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 02:20:22,884] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 02:20:22,884] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:22,884] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 02:20:22,884] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:23,037] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 06:00:00+00:00
[2024-05-22 02:20:23,107] {standard_task_runner.py:52} INFO - Started process 2357 to run task
[2024-05-22 02:20:23,153] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T06:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmptgn3c5rf', '--error-file', '/tmp/tmp5et89jri']
[2024-05-22 02:20:23,250] {standard_task_runner.py:77} INFO - Job 8: Subtask fetch_data
[2024-05-22 02:20:23,831] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [running]> on host 8fe6997c1526
[2024-05-22 02:20:24,132] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T06:00:00+00:00
[2024-05-22 02:20:24,414] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 02:20:24,415] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 02:20:24,467] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T060000, start_date=20240522T022022, end_date=20240522T022024
[2024-05-22 02:20:24,641] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 02:20:24,758] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:14:10,024] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 04:14:10,178] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 04:14:10,178] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:10,178] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:14:10,178] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:10,414] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 06:00:00+00:00
[2024-05-22 04:14:10,511] {standard_task_runner.py:52} INFO - Started process 141 to run task
[2024-05-22 04:14:10,548] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T06:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpdv2y0lt8', '--error-file', '/tmp/tmp9h3mu3_n']
[2024-05-22 04:14:10,655] {standard_task_runner.py:77} INFO - Job 8: Subtask fetch_data
[2024-05-22 04:14:11,147] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:14:11,647] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T06:00:00+00:00
[2024-05-22 04:14:11,655] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:11,738] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T060000, start_date=20240522T041410, end_date=20240522T041411
[2024-05-22 04:14:11,876] {standard_task_runner.py:92} ERROR - Failed to execute job 8 for task fetch_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:11,993] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-22 04:14:12,217] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:17:36,551] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 04:17:36,744] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 04:17:36,745] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:36,746] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:17:36,749] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:36,878] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 06:00:00+00:00
[2024-05-22 04:17:36,958] {standard_task_runner.py:52} INFO - Started process 335 to run task
[2024-05-22 04:17:36,971] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T06:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpxauqjigp', '--error-file', '/tmp/tmpgyl44y6q']
[2024-05-22 04:17:37,017] {standard_task_runner.py:77} INFO - Job 26: Subtask fetch_data
[2024-05-22 04:17:37,702] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:17:38,096] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T06:00:00+00:00
[2024-05-22 04:17:38,112] {logging_mixin.py:109} INFO -  api is None
[2024-05-22 04:17:38,154] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Clast_seen&location_type=0&max_age=300
[2024-05-22 04:17:38,155] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': 'None'}
[2024-05-22 04:17:38,426] {logging_mixin.py:109} INFO - Status Code: 403
[2024-05-22 04:17:38,447] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716351458,
  "error" : "ApiKeyInvalidError",
  "description" : "The provided api_key was not valid."
}
[2024-05-22 04:17:38,581] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 04:17:38,582] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 04:17:38,659] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T060000, start_date=20240522T041736, end_date=20240522T041738
[2024-05-22 04:17:38,886] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 04:17:38,986] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 06:50:07,592] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 06:50:07,709] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 06:50:07,710] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:50:07,712] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 06:50:07,713] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:50:07,750] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 06:00:00+00:00
[2024-05-22 06:50:07,891] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T06:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp92z4i9l3', '--error-file', '/tmp/tmpck59nb4d']
[2024-05-22 06:50:07,972] {standard_task_runner.py:52} INFO - Started process 183 to run task
[2024-05-22 06:50:08,070] {standard_task_runner.py:77} INFO - Job 9: Subtask fetch_data
[2024-05-22 06:50:09,087] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 06:50:09,668] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T06:00:00+00:00
[2024-05-22 06:50:09,693] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 06:50:09,693] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 06:50:09,980] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 06:50:09,981] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716360609,
  "error" : "RateLimitExceededError",
  "description" : "Available API call limit exceeded, please try later."
}{
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716360609,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 06:50:20,837] {logging_mixin.py:109} INFO - Failed to retrieve data: 500
[2024-05-22 06:50:20,848] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 06:50:20,943] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T060000, start_date=20240522T065007, end_date=20240522T065020
[2024-05-22 06:50:21,284] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 06:50:21,793] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 06:59:02,253] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 06:59:02,465] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 06:59:02,465] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:59:02,466] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 06:59:02,466] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:59:02,653] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 06:00:00+00:00
[2024-05-22 06:59:02,800] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T06:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmptm5mdzho', '--error-file', '/tmp/tmpaibtr1wn']
[2024-05-22 06:59:02,838] {standard_task_runner.py:77} INFO - Job 87: Subtask fetch_data
[2024-05-22 06:59:02,720] {standard_task_runner.py:52} INFO - Started process 760 to run task
[2024-05-22 06:59:03,719] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 06:59:04,440] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T06:00:00+00:00
[2024-05-22 06:59:04,502] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 06:59:04,528] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 06:59:04,956] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 06:59:04,959] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361144,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 06:59:05,177] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 06:59:05,179] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 06:59:05,565] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T060000, start_date=20240522T065902, end_date=20240522T065905
[2024-05-22 06:59:05,951] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 06:59:06,314] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:06:49,125] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 07:06:49,397] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 07:06:49,404] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:06:49,405] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:06:49,420] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:06:49,673] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 06:00:00+00:00
[2024-05-22 07:06:49,824] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T06:00:00+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp2h2_q4vp', '--error-file', '/tmp/tmpq3j_pk5l']
[2024-05-22 07:06:49,947] {standard_task_runner.py:77} INFO - Job 167: Subtask fetch_data
[2024-05-22 07:06:49,799] {standard_task_runner.py:52} INFO - Started process 1288 to run task
[2024-05-22 07:06:50,632] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:06:50,937] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T06:00:00+00:00
[2024-05-22 07:06:51,031] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:06:51,064] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:06:51,501] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:06:51,502] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361611,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:06:51,739] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:06:51,766] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:06:51,954] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T060000, start_date=20240522T070649, end_date=20240522T070651
[2024-05-22 07:06:52,273] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:06:52,660] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:14:04,593] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 07:14:04,753] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 07:14:04,754] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:14:04,754] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:14:04,754] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:14:04,869] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 06:00:00+00:00
[2024-05-22 07:14:04,959] {standard_task_runner.py:52} INFO - Started process 1796 to run task
[2024-05-22 07:14:05,031] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T06:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpsebh61x8', '--error-file', '/tmp/tmppigvd2tk']
[2024-05-22 07:14:05,114] {standard_task_runner.py:77} INFO - Job 247: Subtask fetch_data
[2024-05-22 07:14:05,489] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:14:06,088] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T06:00:00+00:00
[2024-05-22 07:14:06,214] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:14:06,224] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:14:06,467] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:14:06,467] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362046,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:14:06,903] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:14:06,906] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:14:07,522] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T060000, start_date=20240522T071404, end_date=20240522T071407
[2024-05-22 07:14:07,808] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:14:09,078] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:16:32,791] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 07:16:32,973] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 07:16:32,988] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:16:32,989] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:16:32,989] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:16:33,140] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 06:00:00+00:00
[2024-05-22 07:16:33,174] {standard_task_runner.py:52} INFO - Started process 1989 to run task
[2024-05-22 07:16:33,256] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T06:00:00+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp0cj4wrlj', '--error-file', '/tmp/tmpsgw5zhpe']
[2024-05-22 07:16:33,314] {standard_task_runner.py:77} INFO - Job 279: Subtask fetch_data
[2024-05-22 07:16:33,853] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:16:34,234] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T06:00:00+00:00
[2024-05-22 07:16:34,280] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:16:34,281] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:16:34,473] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:16:34,474] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362194,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:16:34,618] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:16:34,619] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:16:35,124] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T060000, start_date=20240522T071632, end_date=20240522T071635
[2024-05-22 07:16:35,252] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:16:35,397] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:29:02,125] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 07:29:02,270] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 07:29:02,270] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:29:02,270] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:29:02,270] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:29:02,565] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 06:00:00+00:00
[2024-05-22 07:29:02,659] {standard_task_runner.py:52} INFO - Started process 2739 to run task
[2024-05-22 07:29:02,803] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T06:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpcmp_z75c', '--error-file', '/tmp/tmph47e1gly']
[2024-05-22 07:29:02,879] {standard_task_runner.py:77} INFO - Job 374: Subtask fetch_data
[2024-05-22 07:29:03,651] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:29:04,199] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T06:00:00+00:00
[2024-05-22 07:29:04,325] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:29:04,325] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:29:04,777] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:29:04,831] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362944,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:29:05,339] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:29:05,367] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:29:06,334] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T060000, start_date=20240522T072902, end_date=20240522T072906
[2024-05-22 07:29:06,624] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:29:07,081] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:33:10,681] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 07:33:10,776] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [queued]>
[2024-05-22 07:33:10,776] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:33:10,777] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:33:10,777] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:33:11,004] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 06:00:00+00:00
[2024-05-22 07:33:11,186] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T06:00:00+00:00', '--job-id', '407', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpa7e24tpo', '--error-file', '/tmp/tmpa3qj0h3l']
[2024-05-22 07:33:11,270] {standard_task_runner.py:77} INFO - Job 407: Subtask fetch_data
[2024-05-22 07:33:11,109] {standard_task_runner.py:52} INFO - Started process 2993 to run task
[2024-05-22 07:33:12,072] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T06:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:33:12,824] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T06:00:00+00:00
[2024-05-22 07:33:12,913] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:33:12,918] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:33:13,284] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:33:13,344] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716363193,
  "error" : "RateLimitExceededError",
  "description" : "Available API call limit exceeded, please try later."
}{
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716363193,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:33:13,727] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:33:13,740] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:33:14,372] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T060000, start_date=20240522T073310, end_date=20240522T073314
[2024-05-22 07:33:14,843] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:33:15,962] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
