[2024-05-22 02:20:21,245] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 02:20:21,451] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 02:20:21,451] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:21,451] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 02:20:21,451] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:21,556] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 01:00:00+00:00
[2024-05-22 02:20:21,576] {standard_task_runner.py:52} INFO - Started process 2349 to run task
[2024-05-22 02:20:21,678] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T01:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpqv42mqxr', '--error-file', '/tmp/tmpad_4e5eh']
[2024-05-22 02:20:21,726] {standard_task_runner.py:77} INFO - Job 4: Subtask fetch_data
[2024-05-22 02:20:22,301] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [running]> on host 8fe6997c1526
[2024-05-22 02:20:22,796] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T01:00:00+00:00
[2024-05-22 02:20:23,014] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 02:20:23,015] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 02:20:24,111] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T010000, start_date=20240522T022021, end_date=20240522T022024
[2024-05-22 02:20:24,251] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 02:20:24,409] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:14:08,153] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 04:14:08,269] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 04:14:08,286] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:08,287] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:14:08,288] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:08,377] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 01:00:00+00:00
[2024-05-22 04:14:08,426] {standard_task_runner.py:52} INFO - Started process 132 to run task
[2024-05-22 04:14:08,530] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T01:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmphc02m832', '--error-file', '/tmp/tmppvfawtbz']
[2024-05-22 04:14:08,617] {standard_task_runner.py:77} INFO - Job 3: Subtask fetch_data
[2024-05-22 04:14:08,985] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:14:09,503] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T01:00:00+00:00
[2024-05-22 04:14:09,525] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:09,675] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T010000, start_date=20240522T041408, end_date=20240522T041409
[2024-05-22 04:14:09,821] {standard_task_runner.py:92} ERROR - Failed to execute job 3 for task fetch_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:09,947] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-22 04:14:10,149] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:17:32,603] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 04:17:32,823] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 04:17:32,872] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:32,873] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:17:32,889] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:33,162] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 01:00:00+00:00
[2024-05-22 04:17:33,242] {standard_task_runner.py:52} INFO - Started process 322 to run task
[2024-05-22 04:17:33,441] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T01:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpsmd490yu', '--error-file', '/tmp/tmpd6hb54gh']
[2024-05-22 04:17:33,780] {standard_task_runner.py:77} INFO - Job 21: Subtask fetch_data
[2024-05-22 04:17:34,405] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:17:35,192] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T01:00:00+00:00
[2024-05-22 04:17:35,196] {logging_mixin.py:109} INFO -  api is None
[2024-05-22 04:17:35,274] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Clast_seen&location_type=0&max_age=300
[2024-05-22 04:17:35,275] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': 'None'}
[2024-05-22 04:17:35,639] {logging_mixin.py:109} INFO - Status Code: 403
[2024-05-22 04:17:35,708] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716351455,
  "error" : "ApiKeyInvalidError",
  "description" : "The provided api_key was not valid."
}
[2024-05-22 04:17:35,902] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 04:17:35,924] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 04:17:36,016] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T010000, start_date=20240522T041732, end_date=20240522T041736
[2024-05-22 04:17:36,237] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 04:17:36,345] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 06:50:07,466] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 06:50:07,770] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 06:50:07,773] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:50:07,784] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 06:50:07,789] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:50:07,953] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 01:00:00+00:00
[2024-05-22 06:50:08,050] {standard_task_runner.py:52} INFO - Started process 184 to run task
[2024-05-22 06:50:08,233] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T01:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp_j8oiq34', '--error-file', '/tmp/tmp3oq7598w']
[2024-05-22 06:50:08,316] {standard_task_runner.py:77} INFO - Job 6: Subtask fetch_data
[2024-05-22 06:50:09,028] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 06:50:09,646] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T01:00:00+00:00
[2024-05-22 06:50:09,747] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 06:50:09,747] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 06:50:10,209] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 06:50:10,210] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716360610,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 06:50:20,857] {logging_mixin.py:109} INFO - Failed to retrieve data: 500
[2024-05-22 06:50:20,865] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 06:50:20,994] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T010000, start_date=20240522T065007, end_date=20240522T065020
[2024-05-22 06:50:21,378] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 06:50:21,944] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 06:58:53,173] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 06:58:53,525] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 06:58:53,526] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:58:53,544] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 06:58:53,545] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 06:58:53,788] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 01:00:00+00:00
[2024-05-22 06:58:53,912] {standard_task_runner.py:52} INFO - Started process 736 to run task
[2024-05-22 06:58:54,017] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T01:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpy_oq2ckn', '--error-file', '/tmp/tmp_uvh70fn']
[2024-05-22 06:58:54,140] {standard_task_runner.py:77} INFO - Job 82: Subtask fetch_data
[2024-05-22 06:58:54,863] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 06:58:55,093] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T01:00:00+00:00
[2024-05-22 06:58:55,115] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 06:58:55,128] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 06:58:55,306] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 06:58:55,307] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361135,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 06:58:55,536] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 06:58:55,537] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 06:58:55,898] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T010000, start_date=20240522T065853, end_date=20240522T065855
[2024-05-22 06:58:56,189] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 06:58:56,373] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:06:41,314] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 07:06:41,557] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 07:06:41,557] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:06:41,558] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:06:41,558] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:06:41,745] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 01:00:00+00:00
[2024-05-22 07:06:41,814] {standard_task_runner.py:52} INFO - Started process 1269 to run task
[2024-05-22 07:06:41,887] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T01:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpselzf1lv', '--error-file', '/tmp/tmp563g0e45']
[2024-05-22 07:06:42,000] {standard_task_runner.py:77} INFO - Job 163: Subtask fetch_data
[2024-05-22 07:06:42,491] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:06:43,055] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T01:00:00+00:00
[2024-05-22 07:06:43,112] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:06:43,136] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:06:43,534] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:06:43,536] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716361603,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:06:43,859] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:06:43,860] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:06:44,114] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T010000, start_date=20240522T070641, end_date=20240522T070644
[2024-05-22 07:06:44,468] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:06:45,548] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:14:00,136] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 07:14:00,270] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 07:14:00,270] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:14:00,270] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:14:00,270] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:14:00,449] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 01:00:00+00:00
[2024-05-22 07:14:00,505] {standard_task_runner.py:52} INFO - Started process 1780 to run task
[2024-05-22 07:14:00,535] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T01:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpujiew89c', '--error-file', '/tmp/tmp55kzy1ov']
[2024-05-22 07:14:00,617] {standard_task_runner.py:77} INFO - Job 242: Subtask fetch_data
[2024-05-22 07:14:00,930] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:14:01,400] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T01:00:00+00:00
[2024-05-22 07:14:01,480] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:14:01,509] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:14:02,025] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:14:02,026] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362042,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:14:02,235] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:14:02,236] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:14:02,331] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T010000, start_date=20240522T071400, end_date=20240522T071402
[2024-05-22 07:14:02,428] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:14:02,667] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:16:23,973] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 07:16:24,257] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 07:16:24,300] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:16:24,301] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:16:24,301] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:16:24,505] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 01:00:00+00:00
[2024-05-22 07:16:24,658] {standard_task_runner.py:52} INFO - Started process 1971 to run task
[2024-05-22 07:16:24,732] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T01:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp358244ii', '--error-file', '/tmp/tmp340k4omb']
[2024-05-22 07:16:24,864] {standard_task_runner.py:77} INFO - Job 274: Subtask fetch_data
[2024-05-22 07:16:25,603] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:16:26,494] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T01:00:00+00:00
[2024-05-22 07:16:26,504] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:16:26,504] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:16:26,647] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:16:26,648] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362186,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:16:26,887] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:16:26,892] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:16:27,014] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T010000, start_date=20240522T071624, end_date=20240522T071627
[2024-05-22 07:16:27,234] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:16:27,528] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:28:53,870] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 07:28:54,065] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 07:28:54,066] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:28:54,066] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:28:54,066] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:28:54,305] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 01:00:00+00:00
[2024-05-22 07:28:54,444] {standard_task_runner.py:52} INFO - Started process 2717 to run task
[2024-05-22 07:28:54,495] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T01:00:00+00:00', '--job-id', '370', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpujwmoer0', '--error-file', '/tmp/tmp5twk0t0w']
[2024-05-22 07:28:54,539] {standard_task_runner.py:77} INFO - Job 370: Subtask fetch_data
[2024-05-22 07:28:55,087] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:28:55,383] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T01:00:00+00:00
[2024-05-22 07:28:55,464] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:28:55,468] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:28:55,807] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:28:55,808] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716362935,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:28:56,103] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:28:56,140] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:28:56,303] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T010000, start_date=20240522T072853, end_date=20240522T072856
[2024-05-22 07:28:56,700] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:28:57,099] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22 07:33:04,310] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 07:33:04,499] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [queued]>
[2024-05-22 07:33:04,499] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:33:04,500] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 07:33:04,501] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 07:33:04,529] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 01:00:00+00:00
[2024-05-22 07:33:04,566] {standard_task_runner.py:52} INFO - Started process 2975 to run task
[2024-05-22 07:33:04,602] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T01:00:00+00:00', '--job-id', '402', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpwfbbpkwq', '--error-file', '/tmp/tmpz7atgh6w']
[2024-05-22 07:33:04,656] {standard_task_runner.py:77} INFO - Job 402: Subtask fetch_data
[2024-05-22 07:33:05,381] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T01:00:00+00:00 [running]> on host 148b4063f71c
[2024-05-22 07:33:05,784] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T01:00:00+00:00
[2024-05-22 07:33:05,821] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Ctemperature&location_type=0&max_age=300
[2024-05-22 07:33:05,822] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': '9A23CD90-1279-11EF-B9F7-42010A80000D'}
[2024-05-22 07:33:06,112] {logging_mixin.py:109} INFO - Status Code: 402
[2024-05-22 07:33:06,118] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716363186,
  "error" : "PaymentRequiredError",
  "description" : "Payment is required to make this api call."
}
[2024-05-22 07:33:06,521] {logging_mixin.py:109} INFO - Failed to retrieve data: 402
[2024-05-22 07:33:06,522] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 07:33:07,112] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T010000, start_date=20240522T073304, end_date=20240522T073307
[2024-05-22 07:33:07,337] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 07:33:07,476] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
